### ISSUE TITLE
[Issue]: install TransformerEngine error, cannot reach llvm tar file

### ISSUE THREAD

**Issue by amd-fuweiy** [ROCm/TransformerEngine#50]
### Problem Description

Hi TE team, I'm using This transformer_engine outside of AMD environment, however, when I install as readme, there's an error saying : cannot found https://compute-artifactory.amd.com/artifactory/rocm-generic-local/triton-llvm/aotriton_pytorch_2.3/llvm-49af6502-ubuntu-x64.tar.gz

I checked the file, I can reach the file inside AMD environment, but outside AMD network can't . Could you fix the issue then people outside of AMD can install the TE.

### Operating System

Ubuntu

### CPU

Intel

### GPU

AMD Instinct MI300X

### ROCm Version

ROCm 6.2.0

**Comment by caaatch22** [comment]
same issue

**Comment by wenchenvincent** [comment]
Fixed by https://github.com/ROCm/TransformerEngine/pull/52
